/**
 @Program: To find largest digit in a given number
 @Date: 10/08/2015
 */

/**
 * @author Amit
 *
 */
import java.util.*;
public class LargestDigit {
	
	int max=0;									// variable max is used in method largestDigit to hold largest digit
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		LargestDigit objOne = new LargestDigit();				// Class instantiation
		Scanner sc = new Scanner(System.in);					// Scanner object creation for input
		long number, largestDigit;								//  variable number holds the number and largestDigit will receive the largest digit from the number generated by the recursive method
		System.out.println("Enter Number: ");					// Message for user to input number
		number = sc.nextLong();									// inputting number using Scanner object sc
		largestDigit=objOne.largestdigit(number);				// method invocation and result will be received in variable largestDigit
		System.out.println("Largest Digit is: "+largestDigit);	// Printing the largest digit 
		sc.close();
	}
	
	/* this recursive method takes a number as argument and return the largest digit from that number*/
	public long largestdigit(long number)		
	{
		if(number<0)
		{
			number=number*(-1);
		}
		if(number==0)								
		{
			return max;						// returning the max digit from the method
		}
		else
		{
			int digit=(int)number%10;		// calculates the least significant digit of the number and assign it in variable digit
			if(digit>max)				// condition to compare variable digit with previous maximum digit
			{
				max=digit;				// assign value of digit in variable max if value of digit is greater than value of max
			}
			number=number/10;
			return largestdigit(number);	// recursive calling of method largestdigit
		}	
	}

}
